### ISSUE TITLE
Improve communication during bulk KV uploads

### ISSUE THREAD

**Issue by sureshkumargondi** [cloudflare/wrangler#1041]
#### Environment

* operating system: Mac OS catalina
* output of `rustc -V`:
* output of `node -v`: 13.8.0
* output of `wrangler -V`: 1.7.0

#### Steps to reproduce

When I hit "Wrangler publish" the progress bar just freezes at zero. And doesn't even more. And after all the files get uploaded, I see that full progress completed. 

here is the screenshot of it. 

![Image+2020-02-09+at+9 29 44+PM](https://user-images.githubusercontent.com/611531/74106051-4cd74300-4b89-11ea-96be-f6136a250b7f.png)

**Comment by EverlastingBugstopper** [comment]
Hi @sureshkumargondi - the reason the progress bar is frozen is because Wrangler is making bulk requests to the api which takes a long time. This is expected behavior (but probably not very good behavior) - I think a path forward for this would be to not use the bulk endpoint anymore and instead parallelize the uploads with something like rayon.

For now you'll just have to wait while it uploads.

**Comment by ashleymichal** [comment]
i don't think dropping use of the bulk upload endpoint is a great idea, as it gives a higher level of atomicity than thousands of individual puts can.

**Comment by gabbifish** [comment]
I think we should stick with the bulk uploads. The reality is that, for smaller site uploads, everything can be fit into one bulk upload request (hence the sudden jump from 0% to 100%)! I think we should keep this behavior (using the bulk API endpoint) as is, given that it actually is an accurate representation of the upload behavior happening under the hood.

**Comment by EverlastingBugstopper** [comment]
This is still not a great experience for users since there is no real indication of how long their uploads will take. 

I wonder if there's some way to communicate the upload progress between the API and Wrangler per bulk request. 

At the very least we should output some copy if we detect > a certain number of files that "this may take a few minutes"
