### ISSUE TITLE
Allow a user to specify which wrangler.toml to use with commands

### ISSUE THREAD

**Issue by jroyal** [cloudflare/wrangler#1064]
#### Overview and problem statement

I would like to be able to specify which `wrangler.toml` file to use when running commands like `wrangler publish`. 

I have an example project that I would like to leave an empty toml file in so users can do things like `wrangler generate`. An example repo is https://github.com/cloudflare/worker-template-fetch. However I still want to be able to test it before pushing it out to github, so I need a valid `wrangler.toml` in order to actually publish it. To do that I created a `.gitignored` wrangler.toml that contains my real `wrangler.toml`. 

I currently work around this issue by just changing the names of the template `wrangler.toml` to something else and changing my template to `wrangler.toml` but it would be nice if I could just specify the correct file when running wrangler commands. 

I realize that environments solve most of the problems that having multiple toml files would solve, but in this particular case I don't want to ever commit my toml file to git. So i'm stuck with my current workaround.

#### Basic example

It could work like docker compose, where if you include a `-f` flag it will use that instead of the default `docker-compose.yaml` file.

```wrangler publish -f mywrangler.toml```

**Comment by EverlastingBugstopper** [comment]
Hey so this is something we thought about doing for environments but decided against doing because there are some ways to make templates work without having separate tomls. You can set the environment variables `CF_ACCOUNT_ID` and `CF_ZONE_ID` and leave the `account_id = ""` in your `wrangler.toml` and they will be overridden. If you wanted new team members to know to follow that process, you could have a gitignored `example.wrangler.toml` that has the ids filled in and a comment instructing them to set those environment variables.

That being said, this may still be worth implementing but there'd be a decent bit of cleanup involved (see #478).

What do you think?

**Comment by jroyal** [comment]
Well if it was only account and zone id that would work, but with the release of secrets and environment variables there are some configuration items there that you can't overwrite with system environment variables. So I would still think it would be valuable.
