### ISSUE TITLE
1.8.0-rc.1 needs internet to build locally (-dev)

### ISSUE THREAD

**Issue by tomByrer** [cloudflare/wrangler#1093]
Would be good to document that `wrangler dev` needs internet to build  :)

**Comment by donifer** [comment]
It would be even better if it didn't need to :)

**Comment by EverlastingBugstopper** [comment]
Agreed that it would be ideal if you did not need internet to build with `wrangler dev`, and to be candid - there are no plans to change this.

We have documentation and a blog post about this coming. I did notice that we don't have a super good error message for when you're not connected to the internet so that should also be fixed up.
