### ISSUE TITLE
Error handling for Authentication Error

### ISSUE THREAD

**Issue by exvuma** [cloudflare/wrangler#1105]
#### Steps to reproduce

Wrangler publish does not current catch the `1000` authetication error or reply with any actionable next steps.

For example. I mixed my zone id with account ID and got
```
wrangler publish
Error: [ApiError { code: 10000, message: "Authentication error", other: {} }]
```

#### What did you expect to see?
Once  `wrangler whoiam` supports tokens, we could output much more helpful next steps:
```
$ wrangler publish
Auth error occurred
You have permissions for:
.... whoiam output
And are trying to access
account abcd...
Check your account ID is accurate and the token TOKENNAME has accurate permissions.
```

**Comment by dhaynespls** [comment]
`wrangler whoami` does include some supporting functions to determine permissions that you have so we should be able to leverage the existing logic for posting that information in the case that there is an 10000 auth error with `wrangler publish`. This'll require a bit of a refactor there so that `wrangler publish` can trigger it since at present it's tied to the execution of `whoami`

**Comment by dhaynespls** [comment]
So on wrangler 1.9 the output is actually handled for publish, and in preview we get an (expected) 403.

```
⌘ ~/d/p/hello-world (master)> wrangler publish
💁  JavaScript project found. Skipping unnecessary build!
Error: Your user configuration is invalid, please run wrangler config and enter a new set of credentials.
⌘ ~/d/p/hello-world (master) [1]> wrangler preview
💁  JavaScript project found. Skipping unnecessary build!
Error: HTTP status client error (403 Forbidden) for url (https://api.cloudflare.com/client/v4/accounts/9011e9e88ceef20359f29ea07f8b06dd/workers/scripts/hello-world/preview)
```
