### ISSUE TITLE
Push a single file

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1146]
How can I push a single file? When I use `wrangler publish` it sends all files, but what if I just have a single file I'd like to test?

**Comment by ashleymichal** [comment]
hey @simplenotezy ! I assume you are asking in the context of a `[site]` project.

because of the way we use hashing for cache busting, simply sending a single file to KV isn't terribly straight forward; we use a key value lookup called an "asset manifest" to map url paths to content hashed keys in KV, so any time you update anything for your workers site this manifest must be updated;

that being said, upon publish, we don't _actually_ re-upload all of your files; rather we pull a list of keys from your kv namespace and assess which files have changed based on the content hash and upload accordingly, updating the asset manifest and re-pushing the worker.

is your issue one of speed during development? if so, we have a few tickets around improving the performance of site projects that you might be interested in following [here](https://github.com/cloudflare/wrangler/milestone/26). i'll add this issue to that milestone but it would be great if you could clarify the underlying problem you are looking to solve.

**Comment by simplenotezy** [comment]
Hey @ashleymichal  - thanks for a prompt reply. I am asking because I'd like to set up some redirects using .htaccess and RewriteMap (I have around 3,5k redirects). This file could change day-to-day, without any code changing, and thereby it would be helpful if you could simply push the new .htaccess file with redirects, without having to redeply the whole site (it currently takes around 2-3000 seconds to deploy our site).

**Comment by ashleymichal** [comment]
the way you might get around this now is to create a second kv-namespace entry and use that one for your redirect file; that way syncing your static content will not interfere. This particular file would be subject to the standard caching behavior provided by KV (60 second cache ttl) rather than the caching behavior we built into kv-asset-handler, which uses content hashes to allow us to cache assets indefinitely on the edge and bust them when they're updated. The implication is that, depending on traffic to your worker, your .htaccess file might take up to 60 seconds to become active after you push it, however you will not need to re-publish your worker to update the file. does that sound like a good solution?

**Comment by simplenotezy** [comment]
Thanks for your in-depth answer. It does indeed sound like a good solution, just in need of some more documentation on how I implement this in "real-life"

**Comment by yet-another-dev** [comment]
> [...] it would be great if you could clarify the underlying problem you are looking to solve.

One usecase for this is solving the challenge of "on-the-fly" updates for user-generated (frontend) content (that's built statically, not grabbed at runtime). 

Example:
 
1. A user makes a change on the frontend
2. The site calls a serverless function endpoint that compiles updated version of relevant file(s)
3. The serverless function sends updates file(s) to the `[site]` project (via an API call, likely)

The reason that simply triggering a rebuild doesn't suffice in these cases is because of the significant time between triggering a rebuild and the rebuilt site being deployed.

**Comment by yet-another-dev** [comment]
Actually, for my above-mentioned use case, it looks like utilizing the REST API may be a currently-working/preferrable(?) approach: https://developers.cloudflare.com/workers/tooling/api/routes#update

Not yet tested.

**Comment by ashleymichal** [comment]
@yet-another-dev the api is a valid way to add files, however you could end up with an issue if you later re-deploy your site and the updated content is not present locally, since wrangler "syncs" your kv namespace to match your local files.

**Comment by EverlastingBugstopper** [comment]
site deploys should be significantly faster now, is this feature request still necessary?
