### ISSUE TITLE
Improve route deploy messaging, add `--dry-run` flag

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#1199]
several things can happen when you publish to a route:
1. a new route is created
2. the same route is maintained (it already pointed to the worker you are publishing)
3. the route was already assigned and was not changed
4. some kind of error occurred.

unfortunately only one route can be updated at a time, so there's no way to do an atomic update of all routes, or any kind of a forced overwrite for case 3, so it's up to users to correct these issues. we should:

* add a command or flag that shows the likely outcome of publishing to the routes in question; this output should give the appropriate instructions for correcting instances of case 3. it should also indicate existing routes that are no longer specified in the wrangler.toml as part of this list that can be removed with `wrangler route delete <route>`.
* include the same output on normal publishes to instruct users to `wrangler route delete <route>` for those cases and, in the case of 3, re-run `wrangler publish.`
* ADDED 4/15: include a `--overwrite-routes` flag to automatically delete and re-create routes.

**Comment by glen-au** [comment]
Isn't item 2 just a subset of 3? That is, the worker is updated but the route's assigned worker is not adjusted in either case.

If a user of wrangler is going to be notified to delete the route to then publish to it aren't we creating a potential for an application to be down between delete and publish of the worker at the re-created route?

Surely the question here is why isn't the route, if existing, simply adjusted to use the newly published worker?  The user has defined the route in the wrangler.toml so why shouldn't it be updated? Assuming it can, shouldn't the operation be:
1. worker updated (as current) - note, all routes that use this worker continue to use the now updated worker.
2. specified route (created or existing) is set to use this route

Deploy message then lists the defined route with the former worker name (if changing) and the new worker name.   And, since we are talking about route messages, it would be great if the response could also list all other routes that use the published worker.

This could scale with this same logic should the route variable one day allow multiple routes (delimited list), but this is for another issue.

If it can't be permitted to update an existing route's assigned worker then isn't the "route" field incorrectly titled, and should be renamed to something like "route_create" instead, as this is all its permitted to do.  Then, should this field be present in the wranger.toml file and run where the route exists the suggested message instructions, as per end of first post, would be great to include.  Again, it would be great if the response could also list all other routes that use the published worker.

**Comment by ashleymichal** [comment]
hey @glen-au these  are  some great questions. I'll go a  little out of order and start with saying that we actually do support specifying multiple routes as of 1.8.0. I believe that change lists the routes the worker is deployed on, as well.

> Isn't item 2 just a subset of 3? That is, the worker is updated but the route's assigned worker is not adjusted in either case.

because one is a positive and one is a negative, they are presented as distinct.

> If a user of wrangler is going to be notified to delete the route to then publish to it aren't we creating a potential for an application to be down between delete and publish of the worker at the re-created route?

yes. however this has a lot more to do with the design of the api, as routes cannot be atomically overwritten even at that level, wrangler (or any client) has to make two distinct calls to overwrite a route: one to explicitly delete, and the second to create. i have my eyes on a request to improve the api, but it has not been prioritized by the platform as of yet.

> Surely the question here is why isn't the route, if existing, simply adjusted to use the newly published worker? The user has defined the route in the wrangler.toml so why shouldn't it be updated?

the reason i didn't immediately implement this solution is that a wrangler.toml is not representative of all workers and routes in use at any given time. the route list can give insight, as can the --dry-run option listed here, but to add the destructive step of automatically deleting an existing route would be a breaking change, and one I don't intend to make lightly. I would, however, be open to introducing a flag, such as `--overwrite-routes` to unlock this behavior for users, but it should be noted that until the API changes, the downtime issue you pointed out before will still exist, if only for moments.
