### ISSUE TITLE
Update wrangler to allow subdomain rename

### ISSUE THREAD

**Issue by nprogers** [cloudflare/wrangler#1279]
Changes to the EWC API rolling out soon will allow a user to rename a subdomain. Does wranger need to update as well to allow a rename from CLI?

**Comment by EverlastingBugstopper** [comment]
current usage of `wrangler subdomain` is to print the name of the subdomain you've registered. If you haven't registered one, it says to run `wrangler subdomain <name>`, where `<name>` is the name of the subdomain you want to use. Running `wrangler subdomain <name>` will register a subdomain if you don't have one, and tell you what you've already registered if you have.

Since we've introduced the ability to rename your subdomain, we likely want `wrangler subdomain <name>` to work exactly the same way as it does today, except if you've already registered a subdomain, it should tell you the command you can run to force a rename. My initial thought is that it would be something like `wrangler subdomain <name> --force` that would have a large message warning that what they're doing is destructive (similar to what we do in the UI with all the redeploy messaging) and to type in the name of their old subdomain to delete it (kind of like GitHub does when you delete a repository).

**Comment by ispivey** [comment]
This could be limited to changes to https://github.com/cloudflare/wrangler/blob/master/src/commands/subdomain.rs , or we could also add this API route to https://github.com/cloudflare/cloudflare-rs/tree/master/cloudflare/src/endpoints/workers .

**Comment by ashleymichal** [comment]
closed by #1353
