### ISSUE TITLE
[dev] wrong error when session has expired or package.json is missing

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1292]
### 🐛 Bug Report

It seems `dev` shows this error whenever something goes wrong:
```
Error: Could not upload your script. Check your internet connection or https://www.cloudflarestatus.com/ for rare incidents impacting the Cloudflare Workers API.
```
The first time I took it at face value and tried again a couple of times but it kept failing.

So I tried `wrangler publish` which gave me a token error and I fixed it by simply doing `wrangler config`.

I just got the same error again. I did `wrangler config` but didn't fix it. Again I tried `wrangler publish` and I got the error:
```
Error: Your JavaScript project is missing a `package.json`
```

**Comment by EverlastingBugstopper** [comment]
Hey @PierBover - I think this error squashing should have been fixed in the latest release. Have you upgraded to 1.9.0 and are still seeing this?

As for the `Your JavaScript project is missing a package.json`, you will need a `package.json` with the file you want to upload defined in the `"main"` field. So if you're uploading `index.js`, your package.json would need 

```json
{
  "main": "index.js"
}
```

**Comment by PierBover** [comment]
Hey @EverlastingBugstopper I'm using:

> 👷 ✨  wrangler 1.9.0-rc.0

I do know I need a `package.json` :)

But `dev` should have told me that the issue is a missing `package.json` file or a problem with the session/token, no?

**Comment by EverlastingBugstopper** [comment]
Yup! So the latest version is actually just 1.9.0 so if you upgrade, it _should_ give you the proper error message

**Comment by PierBover** [comment]
Ooops gotcha!

I'll update and reopen if I find the issue again.
