### ISSUE TITLE
Bulk wrangler tail

### ISSUE THREAD

**Issue by davidgagnegarmin** [cloudflare/wrangler#1369]
#### Overview and problem statement

We would like a way to ingest logs for multiple workers without requiring multiple argo tunnels, to make piping them into a centralized log store more efficient. 

#### Basic example

`wrangler.toml` contains env config for all scripts.
`wrangler tail --bulk` streams all worker logs for the account over one argo tunnel.

#### Concerns

This may only work if the scripts are in the same Account since cloudflared seems to be setup per account? Even still this would be an improvement over requiring a new tunnel per tail.

**Comment by ispivey** [comment]
@davidgagnegarmin Thanks for the suggestion! We very much understand and appreciate the need here. 

The Workers team is working on a solution to use the underlying framework behind `wrangler tail` to allow you to send logs to other logging services without having to pipe through wrangler/tunnels first. We'd rather not invest more in making `wrangler` a better tool for automated logging pipelines, since it's intended instead to be an interactive debugging tool.

Hope that makes sense – I'm going to close this issue out, but I'll pass a link on to the team solving this problem more broadly. They may be interested in talking to you.
