### ISSUE TITLE
Rust bindings for Cloudflare KV / Cache APIs

### ISSUE THREAD

**Issue by bluk** [cloudflare/wrangler#1377]
### 💡 Feature request

An easy way to use the Cloudflare Worker runtime specific APIs (e.g. KV and Cache APIs) from Rust.

#### Overview and problem statement

While Rust `web-sys` and `js-sys` crates exist which works for most of the "Worker runtime" environment, there are a few Cloudflare specific APIs which do not have equivalent bindings.

It would be helpful if either Cloudflare or the community could provide an easy to use crate.

**Comment by ispivey** [comment]
This is a good idea! I can't promise when the Workers team can prioritize this, but we've talked about it internally, and would love to see community contributions as well.

**Comment by joepio** [comment]
Since the `needs design` tag is here, perhaps these can offer inspiration for Key/Value store API design:

- [sled](https://docs.rs/sled/0.34.4/sled/), a powerful embedded Key/Value store that mimics `BTreeMap<[u8], [u8]>`.
- [kv](https://docs.rs/kv/0.22.0/kv/) - powered by sled, but easier to use.
- [cask](https://docs.rs/cask/0.7.1/cask/) - another K/V store

**Comment by ffimnsr** [comment]
Is there any update for this? currently there are no examples of using KV on rust-wasm, even just API so we can create a crate for it.

**Comment by koeninger** [comment]
@ffimnsr if you're looking for examples of calling the JS KV api from rust  e.g. https://github.com/koeninger/rust-kv-example/blob/master/src/lib.rs

**Comment by Electroid** [comment]
Going to close this, while it's something we might do, it's not really related to `wrangler`.
