### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by cyberquarks** [cloudflare/wrangler#1708]
#### Overview and problem statement
Currently workers does not seem to support Java from the documentation:
https://developers.cloudflare.com/workers/platform/languages

TeaVM (https://github.com/konsoletyper/teavm) compiled Java to Javascript from the browser does it mean it can be used with Workers?

**Comment by koeninger** [comment]
Java is on our list of languages to look at for adding examples.  There are a lot of Java to JS compilers, without a clear best option.  If you get a TeaVM example working, pull requests to https://github.com/cloudflare/cloudflare-docs are welcome.  In the meantime, I'd suggest trying the Kotlin or Scala examples, as the compile to JS ecosystem is well defined for them.

Closing this since it's not specific to Wrangler.
