### ISSUE TITLE
Failed at the @cloudflare/wrangler@1.12.3 postinstall script.

### ISSUE THREAD

**Issue by amitojsingh366** [cloudflare/wrangler#1713]
#### Environment

* operating system: macOS Big Sur 11.0.1 (20B29)
* output of `rustc -V`:  `rustc 1.49.0 (e1884a8e3 2020-12-29)`
* output of `node -v`:  `v12.19.0`
* output of `wrangler -V`:  `couldn't install wrangler itself...`
* contents of `wrangler.toml`: `couldn't install wrangler itself...`

#### Steps to reproduce
  - Run the command `sudo npm install -g @cloudflare/wrangler`

#### What did you expect to see?
Expected wrangler to be installed
#### What did you see instead?
This issue pops up saying `Failed at the @cloudflare/wrangler@1.12.3 postinstall script.`
*(See screenshot)*
<img width="945" alt="Screen Shot 2021-01-07 at 5 53 35 PM" src="https://user-images.githubusercontent.com/35400192/103906653-45aa1380-5111-11eb-9234-bc8fbafdf586.png">

**Comment by sourcejockey** [comment]
We're having the same issue; hoping for a resolution.

**Comment by xortive** [comment]
Wrangler's `npm` installer doesn't support being run as `root`, such as when using `sudo`, here's why:

The `npm` installer downloads the `wrangler` binary into your machine during the postinstall script, and requires permissions to save the binary in order for it to work. When running `npm install -g` as `root`, `npm` actually runs the postinstall scripts as `nobody`, to prevent malicious postinstall scripts from doing nefarious things with `root` permissions. It's impossible for the `postinstall` script to modify the filesystem when run as `nobody`, and this is why you're seeing a permission error when doing `sudo npm install -g @cloudflare/wrangler`.

The solution here is to use `nvm` to install `node` and `npm`, which will place your global `node_modules` folder in your home directory such that `npm install -g` works without `sudo`, which will make the postinstall script work properly.

After #1780 lands, you could also install wrangler as a dev dependency in your project instead of installing it with `-g`, and use `npx wrangler` to run it.
