### ISSUE TITLE
please add document for install via Homebrew on macOS

### ISSUE THREAD

**Issue by zhangyoufu** [cloudflare/wrangler#1744]
`brew install cloudflare-wrangler` is much simpler than `npm`/`cargo`. And it should work on Apple Silicon as well.

Formula: https://github.com/Homebrew/homebrew-core/commit/3f26f5d3c8fb0bccde75017c3e005c7bb14327d4
Bottle: https://github.com/Homebrew/homebrew-core/commit/756a90ca96aadbf0c1dc8a2655c3bd221d862712

**Comment by Electroid** [comment]
Hi, thanks for working on those PRs! Out of curiosity, is `wrangler` taken?

**Comment by zhangyoufu** [comment]
Yes, `wrangler` was taken by https://github.com/RefactoringTools/wrangler

**Comment by xortive** [comment]
we have a cloudflare-managed homebrew repo at https://github.com/cloudflare/homebrew-cloudflare, I think it makes more sense to have `wrangler` in there as opposed to the greater homebrew repo

**Comment by zhangyoufu** [comment]
> we have a cloudflare-managed homebrew repo at https://github.com/cloudflare/homebrew-cloudflare

I would prefer to install open-source software from homebrew-core, and closed-source software from homebrew-cask. They are widely adopted and more convenient than tapping homebrew-cloudflare. The homebrew-core repo automatically got M1 builds while upstream didn’t provide it.

**Comment by nilslice** [comment]
If you were having trouble installing wrangler on an Apple Silicon / M1 device, it should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

As for the Homebrew integration, that is still yet to be planned. The recommended way to install wrangler is via npm or cargo. I'm going to close this issue for now, but we will keep Homebrew in mind internally for future integrations. Thanks!
