### ISSUE TITLE
Workers Sites with alternative bundler (rollup)?

### ISSUE THREAD

**Issue by boojum** [cloudflare/wrangler#1928]
#### Describe the bug

As per the recent [blog post](https://blog.cloudflare.com/workers-new-custom-builds-and-improved-logging/), cf workers support custom bundlers now. Is this is the case for Workers Sites as well? I'm trying to get it working with `rollup` but no luck so far...

#### Reproduce the bug

1. Clone [repo](https://gitlab.com/b00jum/cf-worker-site-rollup)
2. `cd cf-worker-site-rollup && npm install`
3. `npm run dev` (alias to `wrangler dev`)
4. observe the error:
```
$ wrangler dev

🌀  Running npm install && npm run build

up to date, audited 85 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> build
> rollup -c


src/index.mjs → dist/index.mjs...
created dist/index.mjs in 2.3s
🌀  Using namespace for Workers Site "__worker-site-workers_sites_assets_preview"
✨  Success
Error: HTTP status client error (403 Forbidden) for url (https://api.cloudflare.com/client/v4/accounts/OMITTED/workers/scripts/worker-site/edge-preview)
```

#### Expected behavior

The worker is build and bundled using `rollup`.

#### Environment and versions

* operating system: ubuntu 21.04 
* output of `wrangler -V`: wrangler 1.16.1
* output of `node -v`: v15.14.0
* content of `wrangler.toml`:
```
name = "worker-site"
type = "javascript"
workers_dev = true
account_id = ""
zone_id = ""

[site]
bucket = "public"
entry-point = '.'

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"
```

**Comment by coreybutler** [comment]
I've run into this same error, but arrived at it in a different manner. I've been using wrangler 1.15 since custom builds were first released. It has been running fine for several weeks. All of a sudden, this error shows up when running `npm run dev`. Here are the contents of that page:

![image](https://user-images.githubusercontent.com/770982/119387167-2e1d9280-bc8e-11eb-955e-995d778cc0d4.png)

Again, I made no updates to wrangler and this just started happening with no changes to my code. To me, this suggests there may be a server-side issue.

I tried upgrading wrangler to v1.16.1, but the issue remains. I've logged out/in to no avail.
