### ISSUE TITLE
Golang / tinygo support 

### ISSUE THREAD

**Issue by gedw99** [cloudflare/wrangler#2025]
#### Describe the feature

A clear and concise description of the feature. What problem does it solve for you?

I want to use golang as I use it for most other things such as gui ( web, mobile , desktop ) and so I get code reuse .

#### Describe the alternatives

Are there any alternatives to solving this problem? If so, what was your experience with them?

**Comment by gedw99** [comment]
Would also like to understand why cloud flare does not support golang btw.

**Comment by nilslice** [comment]
Hey @gedw99 - good to cross paths again (feels like a long time since ponzu-cms days)!

I don't see a reason why TinyGo shouldn't work within the Workers runtime (the only restriction is the 1MB wasm binary max size). If you can get an ES module in the browser to run your TinyGo wasm, then it should also work on Workers. We just have not put the time in to document how to do it, or create or integrate any official tooling to automate it (like is the case with Rust). 

Go (without TinyGo) has too large of a runtime to fit within the current 1MB compressed size limitation of the wasm binary. So you may have seen elsewhere that "Workers doesn't support Go", however, that's not the case. It's just that we don't support wasm binaries over 1MB in size. 

If you're interested in trying to make it work, I'd look at how the functionality of the following intersects and contrasts with wasm_exec.js in the Go tree:

- https://github.com/cloudflare/rustwasm-worker-template/blob/master/worker/worker.js#L5-L6
- https://gist.github.com/nilslice/41553dcb25537d68b0856b0a5d2faae3

**Comment by nilslice** [comment]
> my understanding is that CF Workers requires developers to runs WASM with a js api wrapper . This can then run on CF Workers. Is this correct?

Yes, that is correct. Your wasm will communicate with a JS environment (talking to standards-based JS and Cloudflare Workers specific runtime APIs).

**Comment by threepointone** [comment]
I don't believe there's anything actionable here, so I'm going to close this issue.
