### ISSUE TITLE
Wrangler timeout in WSL2

### ISSUE THREAD

**Issue by Moser-ss** [cloudflare/wrangler#2101]
#### Describe the bug

The wrangler CLI timeout every time it tries to interact with the Cloudflare API.
It is similar that issue #1614 but applied to all commands

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Open WSL
2. Open https://dash.cloudflare.com/ in default browser
3. Run `wrangler login`
4. After been authenticated run `wrangler whoami`

Logs from my execution
```bash
 RUST_LOG=debug wrangler whoami
[2021-10-09T21:32:46Z INFO  wrangler::settings::global_config] No $WRANGLER_HOME detected, using $HOME
[2021-10-09T21:32:46Z INFO  wrangler::cli::whoami] Getting User settings
[2021-10-09T21:32:46Z INFO  wrangler::settings::global_config] No $WRANGLER_HOME detected, using $HOME
[2021-10-09T21:32:46Z INFO  wrangler::settings::global_config] Using global config file: /home/smoser/.wrangler/config/default.toml
[2021-10-09T21:32:46Z INFO  wrangler::settings::global_user] Config path exists. Reading from config file, /home/smoser/.wrangler/config/default.toml
[2021-10-09T21:32:46Z DEBUG wrangler::login] Refreshing access token..
[2021-10-09T21:32:46Z DEBUG reqwest::connect] starting new connection: https://crates.io/
[2021-10-09T21:32:46Z DEBUG reqwest::connect] starting new connection: https://api.cloudflare.com/
[2021-10-09T21:33:16Z DEBUG wrangler::version] could not determine if update is needed:
    error sending request for url (https://crates.io/api/v1/crates/wrangler): operation timed out
Error: ⚠️  Error: error sending request for url (https://api.cloudflare.com/client/v4/user): operation timed out
```

#### Expected behavior

Expect the wrangler to finish the commands with sucesss

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows 10 - with WSL2 using Distro Ubuntu 20.04
* output of `wrangler -V`:wrangler 1.19.3
* output of `node -v`:v14.17.6
* content of `wrangler.toml`:

**Comment by snird** [comment]
Can confirm this happens to me too

**Comment by snird** [comment]
I saw different reports on issues and forums every month since 2020.
This doesn't seem to be fixed soon (many issues reported with this has been closed with no real solution)

the only way now seems to be installing node for windows, set up wrangler there, and navigate to the directory of the app in linux through powershell

**Comment by snird** [comment]
This is weird, but it fixed it for me:
I set up the DNS of my wifi to the Cloudflare provided DNS. But the IPv6.
And now it works. might worth your try whoever reads that in the future

**Comment by Moser-ss** [comment]
It is really mind-blowing, I set up the Cloudflare DNS in my system IPv4 and IPv6 and just start work

**Comment by falcon03** [comment]
@Moser-ss  I see you closed the issue, but the bug is still here :(

Using the Cloudflare DNS is not an option for me, and I guess that is true ffor many other environments as well... Therefore not a fix :/

**Comment by 205g0** [comment]
Struggling with this unreproducible bug for weeks and now, after setting all my DNS (both ip4 and ip6) to Cloudflare, everything works smooth as butter.

This must go into the docs or fixed asap. @kentonv, who is the right person for this issue?

**Comment by kentonv** [comment]
I don't know anything about this issue, but just from the comments, it sure sounds like something is wrong with your regular DNS provider, like it is returning the wrong result for api.cloudflare.com. This is probably not an issue the Workers team is positioned to fix, but it would help if you could tell us what DNS provider you are using and what IP it is returning for `api.cloudflare.com`.

With that said, this issue is on Wrangler v1. We released Wrangler v2 more than a year ago and strongly recommend that everyone upgrade. Does the same bug happen in Wrangler 2? If so, maybe you should file a new issue on https://github.com/cloudflare/workers-sdk .

**Comment by 205g0** [comment]
Thanks for the quick reply. I've posted the issue here https://github.com/cloudflare/workers-sdk/issues/3411

This bug is a major dealbreaker for WSL2 users if they aren't aware of the DNS hack.
