### ISSUE TITLE
wrangler.toml routes example

### ISSUE THREAD

**Issue by adaptive** [cloudflare/wrangler#213]
I am having trouble setting routes to
`pub routes: Option<HashMap<String, String>>`

can you show/add to docs example of routes for wrangler.toml? 👏

**Comment by AaronO** [comment]
@adaptive The current `master` does not support publishing multiple routes, I've fixed it here: https://github.com/cloudflare/wrangler/pull/224

Otherwise here's how you define them in your `wranger.toml` (tested locally with my PR's changes):

```toml
[routes]
"sub1.example.com/*" = "worker-script-name" # Should match script variable most of the times
"sub1.example.com/except/*" = "" # Don't route this to any worker
"sub2.example.com/*" = "worker-script-name" # Another subdomain
```

**Comment by xtuc** [comment]
Is there a reason why we need to specifiy the name of the script each time? If we implement #220 that's going to be really error-prone.

If we see the routes as a firewall, I would like to express something like that:
```
[routes]
accept = "sub1.example.com/*"
deny = ["sub1.example.com/wp-admin/*", "sub1.example.com/favicon.ico"]
```

We could even add extra pre-processing on the routes to make it easier:
```
[routes]
accept = "sub1.example.com/{a,b,c}/*"
```

**Comment by AaronO** [comment]
@xtuc I thought about a whitelist/blacklist approach too, I think your suggestion makes sense 👍 

I think in `toml` you could write it as:

```toml
[routes.accept]
"sub1.example.com/*"

[routes.deny]
"sub1.example.com/wp-admin/*"
"sub1.example.com/favicon.ico"
```

The whitelist/blacklist config is not only be less error-prone, but it also prevents leaking API implementation details to the user.

It also solves another issue that bothered me: it felt awkward defining `routes` that are zone-level resources in a `wrangler.toml` file that is meant (for now)to be scoped to a single `script`.

There's a broader question of wrangler's scope (that you breach in #220), i.e: is a single `wrangler` project meant to manage:
a. A single worker
b. Multiple workers in the same zone
c. All the workers in a zone
d. Multiple workers across multiple zones

I think it's important to clarify the scope, sooner rather than later, because it impacts a lot of other design decisions, including #220 (e.g: if we decide that a `wrangler` project is scoped to a single worker, it would make more sense to allow users to specify config files via a `-c, --config` flag instead of bundling multiple workers into the config file and requiring the user to pass a `--env` arg)

**Comment by EverlastingBugstopper** [comment]
This has been released, closing the issue 😄
