### ISSUE TITLE
Allow specifying preview host as option to preview command

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#351]
Currently the preview host is hardcoded to `example.com`. We should allow people to configure it when running `wrangler preview` so they don't have to change it in the UI after the preview window opens.

**Comment by steveklabnik** [comment]
I wonder if we can't use the route for this...

**Comment by EverlastingBugstopper** [comment]
+1 on making this configurable

@steveklabnik this is something we ran into when implementing http events in our serverless framework. It's a little wonky because routes have wildcards - and there may be multiple endpoints (and multiple headers) you want to test with for a given worker. Defaulting to something that triggers the route would be good but I think we should also allow the user to pass in at least a url, if not also the method + headers.

**Comment by rochapablo** [comment]
any update?

**Comment by EverlastingBugstopper** [comment]
@rochapablo you can follow along with this pull request https://github.com/cloudflare/wrangler/pull/1001 and also keep an eye out for an alpha release of `wrangler dev`.

**Comment by EverlastingBugstopper** [comment]
solved by #1001
