### ISSUE TITLE
Don't require different names per environment if they span multiple accounts

### ISSUE THREAD

**Issue by exvuma** [cloudflare/wrangler#554]
### 🐛 Bug Report - Environments
We should not enforce `name` uniqueness if:
* account tags do not much
* using `wrangler preview` ever
#### Steps to reproduce
In wrangler.toml, have both the parent name and the environment name be the same but account tags be different

```
name = "docs-site"
type = "webpack"
account_id = "95e.."
workers_dot_dev = false

# Production
[env.production]
name = "docs-site"
route = "https://blah.com/workers*"
zone_id = "351cf.."
account_id = "b54f..""
```
Even wrangler preview throws:
```
Error: ⚠️  Each name in your `wrangler.toml` must be unique, this name is duplicated: docs-site
```

**Comment by ashleymichal** [comment]
i think this would be as simple as updating the function that validates name uniqueness to take a tuple of `(name, account_id)`, hence the good first issue.

**Comment by drzraf** [comment]
Reopen.
As soon as a worker is needed on more than on domain it starts to be a problem because there is no configuration for this.

If wrangler is not the right tool to deploy routes to multiple domains, then which tool is advised?

**Comment by pbelbin** [comment]
I also am running into this issue.

We have different account ID's for `staging` and `production` environments, and want to be able to use the same deployment name, but are prevented currently from doing this because of the uniqueness checking.

I understand that this would be a problem if the different environments were publishing to the same account, but, in this case, we have *different* accounts.  So the name collision should not be a problem.

Seems the only way around this is to have different `wrangler.toml` and `workers-site/*` files per environment?  Very klunky.

Even a command-line flag to relax the uniqueness checks would be helpful, so that it's specifically being relaxed, and perhaps not a 'default behavior' would be good.

Or, as others have asked, is there a different tool that should be used instead?  If so, which tool should be used?
