### ISSUE TITLE
Specify URL path for wrangler preview

### ISSUE THREAD

**Issue by rdtq** [cloudflare/wrangler#591]
#### Overview and problem statement

Currently there's no option to specify URL path for wrangler preview (that I could find)

Say, we have this route installed for Worker script: `www.example.com/api/*`.

I want preview to handle request to `www.example.com/api/create_user`

#### Basic example

wrangler preview post /api/create_user "user_id=123&name=abc"

**Comment by EverlastingBugstopper** [comment]
Hey! Thanks for the interest, this is something we would love to implement :) We're currently targeting Q4 for this feature. I'm going to close this issue because it is a duplicate of #351. If you'd like to keep up with the work for this, please subscribe to that issue. When a PR is opened, we'll link to it from there.
