### ISSUE TITLE
make and destroy "preview" namespaces

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#599]
on preview, wrangler should push bucket assets to the appropriate namespace. if the user has only one top level environment specified, wrangler should provision a separate kv-namespace (append `--preview` to the standard title name) to allow a user to preview their site without overwriting their uploaded assets.

ALTERNATIVELY

We could assume preview is _only_ for previewing the worker (after all, most static site generators have their own local dev server cli for developing the content itself), and use the same binding, but _not_ upload bucket on preview. This is likely the easiest implementation for MVP.

preview should also support `no-worker` and `no-bucket` flags like publish (see #598 )

**Comment by ashleymichal** [comment]
question: should wrangler clean up after this process? if so, when?

**Comment by gabbifish** [comment]
I think cleanup should be manual, given that `wrangler preview` exits after uploading the worker to the preview service as well as its bindings. It would be bad if we deleted the preview namespace when `wrangler preview` finishes executing, because the preview window on the browser would no longer have access to the preview namespace.

I'm happy with providing documentation on how to delete this `preview` namespace. If we want to roll this into `wrangler`, I guess we could provide a `wrangler preview --clean` that is responsible for deleting this preview namespace, but I think this is pretty unwieldy. I'd rather have folks be responsible for cleaning up a preview namespace (if desired) by using `wrangler kv:namespace delete`.
