### ISSUE TITLE
Errors occasionally have double "Error" string

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#668]
#### Steps to reproduce

Use a bad connection / force timeout on kv uploading

#### What did you expect to see?

```console
$ wrangler publish

🌀  Creating namespace for Workers Site "__www-workers_sites_assets"

Error: https://api.cloudflare.com/client/v4/accounts/f16e4749531f6b3cd0aa857aa043f4f3/storage/kv/namespaces: timed out
```

#### What did you see instead?

```console
$ wrangler publish

🌀  Creating namespace for Workers Site "__www-workers_sites_assets"

Error: Error: https://api.cloudflare.com/client/v4/accounts/f16e4749531f6b3cd0aa857aa043f4f3/storage/kv/namespaces: timed out
```

**Comment by gabbifish** [comment]
This happens because of inconsistent error messages; I think reqwest prepends `Error:` as a prefix when it fails due to things like Timeouts. The KV API itself, however, does not prepend `Error` as a prefix. Wrangler always prepends error messages with `Error: `. This means reqwest errors have Error printed out twice.

 Focusing on bigger fish to fry at the moment, but this is an excellent candidate for a fix if anyone has spare cycles :)
