### ISSUE TITLE
don't install wasm-pack for webpack projects

### ISSUE THREAD

**Issue by TownLake** [cloudflare/wrangler#745]
#### Environment

* operating system: macOS Mojav 10.14.6
* output of `rustc -V`: rustc 1.38.0 (625451e37 2019-09-23)
* output of `node -v`:
* output of `wrangler -V`: 👷 ✨  wrangler 1.4.0

#### Steps to reproduce

I have a static site generated from Hugo and am attempting to publish with Wrangler. It worked the first few times, but timed out trying to get to crates.io

#### What did you expect to see?

Publish success

#### What did you see instead?

`Total in 30 ms
C02WF0XWHV2R:blog-samrhea samrhea$ wrangler publish
🌀  Using namespace for Workers Site "__blog-samrhea-workers_sites_assets"
💁  ignoring file .DS_Store
💁  ignoring file .DS_Store
💁  Uploading...
✨  Success
⬇️ Installing wranglerjs...
Error: https://crates.io/api/v1/crates/wasm-pack: error trying to connect: connect timed out`

**Comment by ashleygwilliams** [comment]
seems like crates.io may have had some down time or an incident when this happened. the real bug here is that it was attempting to install wasm-pack but it didn't need to be. this is similar to https://github.com/cloudflare/wrangler/issues/768! @EverlastingBugstopper as you work on 768 can you also take a look at this? will be in the exact same part of the (bad) code (i wrote) :P

**Comment by berstend** [comment]
Same issue here - a way to bypass wasm dependencies would be great (don't need them)
```⬇️ Installing wranglerjs...
Error: https://crates.io/api/v1/crates/wasm-pack: error trying to connect: connect timed out```

**Comment by EverlastingBugstopper** [comment]
first attempt to do this in #849 didn't pan out. will try again with a new approach
