### ISSUE TITLE
Installing on every change wasm-pack / wranglerjs

### ISSUE THREAD

**Issue by shyim** [cloudflare/wrangler#768]
### 🐛 Bug Report

When i run `wrangler preview --watch` it's installing on every change those packages. Is that normal? It takes lot of time on every change.

#### Environment

* operating system: NixOs
* output of `rustc -V`: Is not installed
* output of `node -v`: v12.5.0
* output of `wrangler -V`: wrangler 1.4.0

#### Steps to reproduce

Empty new Project and then preview it with watch

#### What did you expect to see?
Faster loading without installing on every change that package

#### What did you see instead?
Taking time on every change to install that package

**Comment by lolcoolkat** [comment]
Bump! Would like a way to not have to install wrangler and wasm-pack every time I publish my worker. I'm not even using wasm-pack for my worker!

**Comment by EverlastingBugstopper** [comment]
currently we check to see if the latest version of the binary we need is [installed on the system](https://github.com/cloudflare/wrangler/blob/master/src/install/mod.rs#L56). We need to instead check if the latest version is installed in the [install directory](https://github.com/cloudflare/wrangler/blob/master/src/install/mod.rs#L28). this is difficult because our install directory is full of things like `wranglerjs-789087` that don't have the version names in the directories. 

1) When we download, we should put the version number in the directory number
2) When we check if we need an install, we should see if the version number already exists in the download folder (optionally also check the system version)
3) If there is an updated version we need to install, we should install that and clean up the old one

**Comment by ispivey** [comment]
🥳 This is awesome!

**Comment by protoEvangelion** [comment]
@EverlastingBugstopper this is still happening for me when running `wrangler dev`. Is there something I need to install locally?

![image](https://user-images.githubusercontent.com/20076677/95641339-86cd5180-0a56-11eb-826e-750165ff9a70.png)

**Comment by EverlastingBugstopper** [comment]
Sorry, I don't work at Cloudflare anymore. Might be worth opening a new issue for it 😁
