### ISSUE TITLE
Remove warnings for dead code in cargo test

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#818]
```console
$ cargo test           
warning: constant item is never used: `BUNDLE_OUT`
  --> tests/utils/mod.rs:14:1
   |
14 | const BUNDLE_OUT: &str = "./worker";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: function is never used: `fixture_out_path`
  --> tests/utils/mod.rs:37:1
   |
37 | pub fn fixture_out_path(fixture: &str) -> PathBuf {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function is never used: `webpack_config`
  --> tests/utils/mod.rs:58:1
   |
58 | pub fn webpack_config(fixture: &str, config: &str) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This code _is_ used which makes this very confusing. [This issue](https://github.com/rust-lang/rust/issues/46379) seems related but I can't make heads nor tails of it.

**Comment by pradovic** [comment]
Hi! 
It looks like the issue is related indeed. However, what is missing in the issue responses is that if your functions are public, this can be used by `pub mod` declaration, as unused warning should be suppressed for public mod/fn. I have opened a PR with the suggested approach: https://github.com/cloudflare/wrangler/pull/832. 
Let me know does it makes sense :) Cheers!
