### ISSUE TITLE
 `wrangler whoami` cannot print out email for users using API tokens

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#863]
Because the /user Cloudflare v4 API endpoint doesn't support API tokens yet, we can't retrieve a user's email using their API token. This means `wrangler whoami` won't be able to provide the expected email output for API token users (an error message informing users of this is currently printed out).

**Comment by dhaynespls** [comment]
The new default cloudflare workers API token template includes the required permission in order to do this lookup: 
![image](https://user-images.githubusercontent.com/10170354/79007933-242fe300-7b11-11ea-9244-3942fab34c2a.png)

I'm thinking the output including your email should look something like the following to mirror the output of using the global API token:
```
⌘ ~> wrangler whoami

👋  You are logged in with an API Token, associated with the email 'dhaynes@cloudflare.com'.

+------------------------------------------+----------------------------------+
| Account Name                             | Account ID                       |
+------------------------------------------+----------------------------------+
| My Security Team Testing Account | ... accountID ... |
+------------------------------------------+----------------------------------+
```

I'll work on a PR for this!
