### ISSUE TITLE
include asset manifest in worker site built script size

### ISSUE THREAD

**Issue by guaka** [cloudflare/wrangler#896]
### 🐛 Bug Report

```
 Uploading...
 Uploading...
 Success
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 11 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10027,
      "message": "workers.api.error.script_too_large"
    }
  ],
  "messages": []
}
```

#### Environment

* ubuntu
* output of `rustc -V`: not found: rustc
* output of `node -v`: v10.17.0
* output of `wrangler -V`: wrangler 1.6.0

#### Steps to reproduce

`wrangler publish --verbose --env=prod`

on a directory with 60k+ files of size  4.2G.

#### What did you expect to see?

Success

#### What did you see instead?

`      "message": "workers.api.error.script_too_large"`

**Comment by ashleymichal** [comment]
hey @guaka !

This issue reveals an interesting bug in how wrangler calculates build size. The workers platform calculates your project's bundle size based on the total size of the script and all of its embedded assets, including wasm modules and text blobs. The way we handle cache invalidation for Workers Sites is by generating an asset manifest that maps paths to kv keys, and the kv keys include a content hash to "fingerprint" them as unique cache keys. We bundle that asset manifest as a text blob binding when we upload your worker, and the size of that text blob counts against the 1MB bundle size limit.

I can imagine that a project with 60k+ assets could potentially come up against that limit.

There are a few ways we can try to alleviate this issue, but at minimum we should include the generated asset manifest in our bundle size calculations during a build so that our warn is still effective. we should also adjust the messaging to include the size of individual assets (script, wasm module, text blob) as an itemized set to show folks where their size issues are.

**Comment by guaka** [comment]
Cool. That makes sense.

A related issue is that `Uploading...` takes quite a while. It would be nice if there was some kind of indication of what it's uploading or how many files have been uploaded so far.

(I also posted 2 other queries at https://community.cloudflare.com/u/fifi/activity)

**Comment by tmikaeld** [comment]
This is an ongoing struggle for Cloudflare it seems, we hit a lot of API 500 errors today that came and went for a few hours. I'm wondering if they can handle it, considering that CF workers are growing in popularity.

**Comment by sureshkumargondi** [comment]
@ashleymichal Hey Ashley, Can you explain how to do that in simple way? I got into same issue, when I'm uploading 14Gig of hugo based static site. 

> There are a few ways we can try to alleviate this issue, but at minimum we should include the generated asset manifest in our bundle size calculations during a build so that our warn is still effective. we should also adjust the messaging to include the size of individual assets (script, wasm module, text blob) as an itemized set to show folks where their size issues are.

**Comment by ashleymichal** [comment]
so, the solution to this particular issue will only address giving the user a warning explaining where their size issues  are. The asset manifest is generated by wrangler, though, and users don't have control over that. There are other issues open to address optimizing the size of the asset manifest, for example: #897 i may be getting a little time to address those in the next few weeks.

**Comment by ashleymichal** [comment]
this should stay.

**Comment by ashleymichal** [comment]
what i think would actually be most effective here would be to include the gzipped asset sizes in the error message from the API, giving users an actionable message without duplicating the compression logic in wrangler. marking this as cross-team: API
