### ISSUE TITLE
[dev] Display status code in wrangler dev request output

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/wrangler#930]
#### Overview and problem statement

Currently, preview outputs:
```
[2019-12-05 13:41:40] "GET example.com/ HTTP/1.1"
```

Would be useful to see the status code in there so you know if the request was successful

#### Basic example

```
[2019-12-05 13:41:40] "GET example.com/ HTTP/1.1 200" 
```

**Comment by bradyjoslin** [comment]
OK if the response status is provided on a new line prefixed with `>`?  Have this running locally, happy to provide a PR.

```
 JavaScript project found. Skipping unnecessary build!
 watching "./"
 Listening on http://localhost:8787
[2020-02-16 13:53:13] GET example.com/ HTTP/1.1
> HTTP/1.1 200 OK
[2020-02-16 13:53:21] GET example.com/hello HTTP/1.1
> HTTP/1.1 200 OK
```

**Comment by EverlastingBugstopper** [comment]
Hey @bradyjoslin - this one's tough! I took a look at doing this a while back and wasn't satisfied with the 200 on a newline because it's possible that `console.log` messages get interleaved in between the request line and the response line. If you can figure out how to get them on the same line I'd love a PR 😄
