### ISSUE TITLE
Remove  logging for "JavaScript project found. Skipping unnecessary build"

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#978]
Remove logging for "JavaScript project found. Skipping unnecessary build"

**Comment by EverlastingBugstopper** [comment]
We should replace this with "Built successfully" so that the output of `wrangler build` is not completely empty

**Comment by ashleymichal** [comment]
so i think what we should  do is extract the functionality of build out into its own top level module and  leave the print statements in the commands; then we call build::do from the build command and the publish command,  rather than calling  the build  command from the  publish command, and each command can  then be  in  charge of its own printing.
